//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace ManageTerritories {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class territoriesDataset : DataSet {
        
        private TerritoriesDataTable tableTerritories;
        
        public territoriesDataset() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected territoriesDataset(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Territories"] != null)) {
                    this.Tables.Add(new TerritoriesDataTable(ds.Tables["Territories"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TerritoriesDataTable Territories {
            get {
                return this.tableTerritories;
            }
        }
        
        public override DataSet Clone() {
            territoriesDataset cln = ((territoriesDataset)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Territories"] != null)) {
                this.Tables.Add(new TerritoriesDataTable(ds.Tables["Territories"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableTerritories = ((TerritoriesDataTable)(this.Tables["Territories"]));
            if ((this.tableTerritories != null)) {
                this.tableTerritories.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "territoriesDataset";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/territoriesDataset.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableTerritories = new TerritoriesDataTable();
            this.Tables.Add(this.tableTerritories);
        }
        
        private bool ShouldSerializeTerritories() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void TerritoriesRowChangeEventHandler(object sender, TerritoriesRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TerritoriesDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnTerritoryID;
            
            private DataColumn columnTerritoryDescription;
            
            private DataColumn columnRegionID;
            
            internal TerritoriesDataTable() : 
                    base("Territories") {
                this.InitClass();
            }
            
            internal TerritoriesDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn TerritoryIDColumn {
                get {
                    return this.columnTerritoryID;
                }
            }
            
            internal DataColumn TerritoryDescriptionColumn {
                get {
                    return this.columnTerritoryDescription;
                }
            }
            
            internal DataColumn RegionIDColumn {
                get {
                    return this.columnRegionID;
                }
            }
            
            public TerritoriesRow this[int index] {
                get {
                    return ((TerritoriesRow)(this.Rows[index]));
                }
            }
            
            public event TerritoriesRowChangeEventHandler TerritoriesRowChanged;
            
            public event TerritoriesRowChangeEventHandler TerritoriesRowChanging;
            
            public event TerritoriesRowChangeEventHandler TerritoriesRowDeleted;
            
            public event TerritoriesRowChangeEventHandler TerritoriesRowDeleting;
            
            public void AddTerritoriesRow(TerritoriesRow row) {
                this.Rows.Add(row);
            }
            
            public TerritoriesRow AddTerritoriesRow(string TerritoryID, string TerritoryDescription, int RegionID) {
                TerritoriesRow rowTerritoriesRow = ((TerritoriesRow)(this.NewRow()));
                rowTerritoriesRow.ItemArray = new object[] {
                        TerritoryID,
                        TerritoryDescription,
                        RegionID};
                this.Rows.Add(rowTerritoriesRow);
                return rowTerritoriesRow;
            }
            
            public TerritoriesRow FindByTerritoryID(string TerritoryID) {
                return ((TerritoriesRow)(this.Rows.Find(new object[] {
                            TerritoryID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                TerritoriesDataTable cln = ((TerritoriesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new TerritoriesDataTable();
            }
            
            internal void InitVars() {
                this.columnTerritoryID = this.Columns["TerritoryID"];
                this.columnTerritoryDescription = this.Columns["TerritoryDescription"];
                this.columnRegionID = this.Columns["RegionID"];
            }
            
            private void InitClass() {
                this.columnTerritoryID = new DataColumn("TerritoryID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTerritoryID);
                this.columnTerritoryDescription = new DataColumn("TerritoryDescription", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTerritoryDescription);
                this.columnRegionID = new DataColumn("RegionID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegionID);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnTerritoryID}, true));
                this.columnTerritoryID.AllowDBNull = false;
                this.columnTerritoryID.Unique = true;
                this.columnTerritoryDescription.AllowDBNull = false;
                this.columnRegionID.AllowDBNull = false;
            }
            
            public TerritoriesRow NewTerritoriesRow() {
                return ((TerritoriesRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new TerritoriesRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(TerritoriesRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TerritoriesRowChanged != null)) {
                    this.TerritoriesRowChanged(this, new TerritoriesRowChangeEvent(((TerritoriesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TerritoriesRowChanging != null)) {
                    this.TerritoriesRowChanging(this, new TerritoriesRowChangeEvent(((TerritoriesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TerritoriesRowDeleted != null)) {
                    this.TerritoriesRowDeleted(this, new TerritoriesRowChangeEvent(((TerritoriesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TerritoriesRowDeleting != null)) {
                    this.TerritoriesRowDeleting(this, new TerritoriesRowChangeEvent(((TerritoriesRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveTerritoriesRow(TerritoriesRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TerritoriesRow : DataRow {
            
            private TerritoriesDataTable tableTerritories;
            
            internal TerritoriesRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableTerritories = ((TerritoriesDataTable)(this.Table));
            }
            
            public string TerritoryID {
                get {
                    return ((string)(this[this.tableTerritories.TerritoryIDColumn]));
                }
                set {
                    this[this.tableTerritories.TerritoryIDColumn] = value;
                }
            }
            
            public string TerritoryDescription {
                get {
                    return ((string)(this[this.tableTerritories.TerritoryDescriptionColumn]));
                }
                set {
                    this[this.tableTerritories.TerritoryDescriptionColumn] = value;
                }
            }
            
            public int RegionID {
                get {
                    return ((int)(this[this.tableTerritories.RegionIDColumn]));
                }
                set {
                    this[this.tableTerritories.RegionIDColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TerritoriesRowChangeEvent : EventArgs {
            
            private TerritoriesRow eventRow;
            
            private DataRowAction eventAction;
            
            public TerritoriesRowChangeEvent(TerritoriesRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public TerritoriesRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
